lineproto: support zlib
direct-connect/go-dc pull request #8
Opened 2019-03-14 17:35 UTC by gswly

This is hard but necessary.

Zlib is used in both NMDC and ADC:
* for transferring files
* for hub-to-client communication, between $ZOn| and a zlib EOF.

Zlib is also (IMHO) the main feature that indicates that the protocol is old and conceived a long time ago: its activation and deactivation on a single message depends on the content of the previous message.
Parallel parsing and processing of messages (basically the main feature of Go) is not possible, messages have to be FIRST parsed and the processed, because the following message could be compressed and require deflating.

This PR replicates the solution i implemented in dctk, and introduces a 3-level line reader:
* in the first level, bytes are buffered
* in the second level, bytes are deflated if compression is active
* in the third level, bytes are read until the delimiter, byte by byte, STRICTLY without buffering

Please test carefully this patch with the hub and feel free to propose changes.

2019-03-14 19:06 UTC, dennwc requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/direct-connect/go-dc/8)* status: all files reviewed, 7 unresolved discussions (waiting on @gswly)

___
*[lineproto/reader.go, line 56 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xPPlI6oA4fgXU2Qb3:-L_xPPlI6oA4fgXU2Qb4:b-r9ike3) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader.go#L56)):*
> ```Go
> 			c.zlibReader.Close()
> 			c.activeReader = c.in
> 			continue
> ```

This cannot happen more than once, so it may be better to repeat the `n, err := c.activeReader.Read(buf)` line here and remove the loop.
___
*[lineproto/reader.go, line 115 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xPukeES71M8pOL8iB:-L_xPukeES71M8pOL8iC:b-8rmfgs) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader.go#L115)):*
> ```Go
> // call to Read or ReadLine.
> func (r *Reader) ReadLine() ([]byte, error) {
> 	if r.Safe == false {
> ```

"Not safe" (`!r.Safe`) is more readable than "safe is equal to false" (`r.Safe == false`). I think I've seen it in the Go style convention as well.
___
*[lineproto/reader.go, line 120 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xQ9QQ6UxxjNu9_dHQ:-L_xQ9QQ6UxxjNu9_dHR:b5t765a) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader.go#L120)):*
> ```Go
> 	}
> 
> 	buf := make([]byte, maxLine)
> ```

Allocating a new buffer with a full size each time is very slow.
___
*[lineproto/reader.go, line 128 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xQgAY2cmaD9YQGpjL:-L_xQgAY2cmaD9YQGpjM:b-p2racq) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader.go#L128)):*
> ```Go
> 
> 		// read one character at a time
> 		read, err := r.in.Read(buf[offset : offset+1])
> ```

Reading byte-by-byte will ruin the performance for sure. It may not matter too much for the client, but it has a huge effect on the hub that needs to keep 1000-s of those connections.

I propose to partially revert the change to `Reader`. 

First, we need to make a copy of `bufio.Reader`, so we can ask it to expose an internal buffer. Then, make a first commit that uses this reader instead of the current internal buffer. Instead of searching for delimiter byte-by-byte, ask our new `bufReader` for the slice of buffered data and try to find the delimiter there with `bytes.IndexByte`. Same as it does right now.

The second commit will be about adding compression to this.

When compression is enabled, it should take the current `bufReader` from the line reader, and use it directly (it supports `ReadByte`). The line reader will make a second `bufReader` to wrap the zlib reader.

When EOF is encountered, zlib reader may still have some (uncompressed) data remaining, so it should append it to the current buffer of the line reader. If implemented correctly, the line reader should have an empty buffer, so we can discard it freely.

This can be combined with `sync.Pool` to maximize performance. If `ZOn` happens often, we can also keep the second buffer around, so instead of making a new one for zlib reader, we can pick an old one that was left from line reader (when disabling compression).


Let me know if it sounds too complicated - I will make this change myself then.
___
*[lineproto/reader.go, line 154 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xUVv63mJoQ2kqgDUD:-L_xUVv63mJoQ2kqgDUE:b-pogh4h) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader.go#L154)):*
> ```Go
> }
> 
> // ActivateCompression activates zlib deflating.
> ```

`EnableZLib` activates zlib deflating for messages.

Zlib might also be used for the whole line reader when using it for transferring data (we should add a `Read` method at some point).
___
*[lineproto/reader_test.go, line 21 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xUBOu-rIG_weUOcIH:-L_xUBOu-rIG_weUOcII:b-d0wnfr) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader_test.go#L21)):*
> ```Go
> 	l1Expected := []byte("$ZOn|")
> 	l1, err := r.ReadLine()
> 	if err != nil {
> ```

`require.NoError(t, err)`
___
*[lineproto/reader_test.go, line 24 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xUHSzA1hvcuA-anuK:-L_xUHSzA1hvcuA-anuL:b-z4h34r) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader_test.go#L24)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	if reflect.DeepEqual(l1, l1Expected) == false {
> ```

`require.Equal(l1Expected, l1)`
it will also write a nice diff if they are different


<!-- Sent from Reviewable.io -->

2019-03-14 22:22 UTC, gswly commented
I did everything including the double buffer procedure, but i did not use a custom read buffer, just the standard one.

> When EOF is encountered, zlib reader may still have some (uncompressed) data remaining

i checked, and if the buffers are implemented correctly, the zlib reader never have uncompressed data remaining. Any uncompressed data is left in the previous buffer. So it is possible to skip the building of a custom buffer.

2019-03-14 23:27 UTC, dennwc reviewed
You also mentioned the file transfer. Do you want to expose the `Read` method as well (that can use `ReadByte` for now)? 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/direct-connect/go-dc/8#-:-L_yWXIXBcn_IQV0PBoX:bipfs1m)* status: all files reviewed, 2 unresolved discussions (waiting on @gswly)

___
*[lineproto/reader.go, line 128 at r1](https://reviewable.io/reviews/direct-connect/go-dc/8#-L_xQgAY2cmaD9YQGpjL:-L_yVu8xAAH2qKLg0Xj8:bbpuyj9) ([raw file](https://github.com/direct-connect/go-dc/blob/1d9dc9482e63518a695d822c78086d088e7df45e/lineproto/reader.go#L128)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Reading byte-by-byte will ruin the performance for sure. It may not matter too much for the client, but it has a huge effect on the hub that needs to keep 1000-s of those connections.

I propose to partially revert the change to `Reader`. 

First, we need to make a copy of `bufio.Reader`, so we can ask it to expose an internal buffer. Then, make a first commit that uses this reader instead of the current internal buffer. Instead of searching for delimiter byte-by-byte, ask our new `bufReader` for the slice of buffered data and try to find the delimiter there with `bytes.IndexByte`. Same as it does right now.

The second commit will be about adding compression to this.

When compression is enabled, it should take the current `bufReader` from the line reader, and use it directly (it supports `ReadByte`). The line reader will make a second `bufReader` to wrap the zlib reader.

When EOF is encountered, zlib reader may still have some (uncompressed) data remaining, so it should append it to the current buffer of the line reader. If implemented correctly, the line reader should have an empty buffer, so we can discard it freely.

This can be combined with `sync.Pool` to maximize performance. If `ZOn` happens often, we can also keep the second buffer around, so instead of making a new one for zlib reader, we can pick an old one that was left from line reader (when disabling compression).


Let me know if it sounds too complicated - I will make this change myself then.
</blockquote></details>

Awesome, thanks! It looks way better now :)

Still, I want to take some time to make a benchmark to see how the byte-by-byte copy affects the performance. I'm pretty sure it slows things down significantly, but I can improve it later as a separate PR.


<!-- Sent from Reviewable.io -->

2019-03-14 23:41 UTC, gswly commented
ReadByte() and the buffer can be replaced by ReadBytes(delim) https://golang.org/pkg/bufio/#Reader.ReadBytes that surely improves performance.

if a custom buffer further improves performance, we can use it instead.

2019-03-14 23:44 UTC, gswly commented
Regarding file transferring, we’ll see another day if it’s better to expose Read() or to bypass lineproto

2019-03-15 00:01 UTC, dennwc approved these changes
OK, then I merging this one. Thanks again! :)

Regarding the file reader, there is an alternative approach: to make a function similar to [this one](https://github.com/direct-connect/go-dcpp/blob/master/adc/conn.go#L499) to allow to "hijack" a reader to transfer a specific amount of bytes. Since the file/chunk size is always known in advance, this can be done easily. It may help to keep connection ownership to line reader and avoid overruns for a client that tries to read the file.

> *[Reviewable](https://reviewable.io/reviews/direct-connect/go-dc/8#-:-L_ycN5L7J3kwt8RoN2X:bvqpl5q)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-03-15 00:01 UTC, merged